<?xml version="1.0"?>
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
  <channel>
    <title>CKAN: Ticket #1809: Catch request exceptions in archiver link_checker task</title>
    <link>http://localhost/ticket/1809</link>
    <description>&lt;p&gt;
Some request exceptions are currently not being caught (see the celery log on thedatahub for examples)
&lt;/p&gt;
</description>
    <language>en-us</language>
    <image>
      <title>CKAN</title>
      <url>http://assets.okfn.org/p/ckan/img/ckan_logo_shortname.png</url>
      <link>http://localhost/ticket/1809</link>
    </image>
    <generator>Trac 0.12.3</generator>
    <item>
      
        <dc:creator>johnglover</dc:creator>

      <pubDate>Wed, 29 Feb 2012 15:20:28 GMT</pubDate>
      <title>status changed; resolution set</title>
      <link>http://localhost/ticket/1809#comment:1</link>
      <guid isPermaLink="false">http://localhost/ticket/1809#comment:1</guid>
      <description>
          &lt;ul&gt;
            &lt;li&gt;&lt;strong&gt;status&lt;/strong&gt;
                changed from &lt;em&gt;new&lt;/em&gt; to &lt;em&gt;closed&lt;/em&gt;
            &lt;/li&gt;
            &lt;li&gt;&lt;strong&gt;resolution&lt;/strong&gt;
                set to &lt;em&gt;fixed&lt;/em&gt;
            &lt;/li&gt;
          &lt;/ul&gt;
        &lt;p&gt;
Caught exceptions in QA instead, error message stored as openness_score_reason
&lt;/p&gt;
      </description>
      <category>Ticket</category>
    </item>
 </channel>
</rss>